/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CategoriesSidebar: typeof import('./src/components/CategoriesSidebar.vue')['default']
    Checkout: typeof import('./src/components/modal/Checkout.vue')['default']
    copy: typeof import('./src/components/CategoriesSidebar copy.vue')['default']
    FiturSidebar: typeof import('./src/components/FiturSidebar.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Headers: typeof import('./src/components/Headers.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/hero/Hero.vue')['default']
    Login: typeof import('./src/components/modal/Login.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    ProductsList: typeof import('./src/components/ProductsList.vue')['default']
    ProductsListContainer: typeof import('./src/components/products_list/ProductsListContainer.vue')['default']
    Produk: typeof import('./src/components/produk.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/Search.vue')['default']
    Signup: typeof import('./src/components/modal/Signup.vue')['default']
    Subheader: typeof import('./src/components/subheader/Subheader.vue')['default']
  }
}
