/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/cart/': RouteRecordInfo<'/cart/', '/cart', Record<never, never>, Record<never, never>>,
    '/dashboard/kategori/': RouteRecordInfo<'/dashboard/kategori/', '/dashboard/kategori', Record<never, never>, Record<never, never>>,
    '/dashboard/produk/': RouteRecordInfo<'/dashboard/produk/', '/dashboard/produk', Record<never, never>, Record<never, never>>,
    '/index copy 2': RouteRecordInfo<'/index copy 2', '/index copy 2', Record<never, never>, Record<never, never>>,
    '/orders/': RouteRecordInfo<'/orders/', '/orders', Record<never, never>, Record<never, never>>,
    '/products/[id]': RouteRecordInfo<'/products/[id]', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/user/wishlist/': RouteRecordInfo<'/user/wishlist/', '/user/wishlist', Record<never, never>, Record<never, never>>,
  }
}
